name: chip-tool 
version: "0.1"
summary: matter for HA prelim snap
description: |
  Matter repo provides code for matter middleware and there are lot of examples based on operational features for home utilities. This snap tries to provide
  matter controller(chip-tool).   
confinement: strict
base: core22
grade: stable
license: Apache-2.0 #not sure whether this is right
architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64
assumes:
  - snapd2.46
parts:
  matter-dev:
    source: https://github.com/project-chip/connectedhomeip.git #connectedhomeip 
    plugin: nil
    override-pull: |
     echo "just do nothing"
     #ln -sf ${CRAFT_PROJECT_DIR}/connectedhomeip connectedhomeip
    override-build: |
      set +u	
      echo "I am in dir `pwd`"
      git clone --recurse-submodules https://github.com/project-chip/connectedhomeip.git .
      git submodule update --init	
      #cp -arfT $CRAFT_PROJECT_DIR/connectedhomeip $CRAFT_PART_BUILD/
     
      #mv $CRAFT_PROJECT_DIR/bakup/*  $CRAFT_PART_BUILD/
      source scripts/activate.sh

      gn gen out/host1

      ninja -C out/host1
      cp -ar out/host1/chip-* $CRAFT_PART_INSTALL/
      cp out/host1/spake2p  $CRAFT_PART_INSTALL/
      cp out/host1/address-resolve-tool $CRAFT_PART_INSTALL/
      cp out/host1/obj/src/qrcodetool/bin/qrcodetool $CRAFT_PART_INSTALL/  
      cp -ar out/host1/lib    $CRAFT_PART_INSTALL/
    build-packages: [git, gcc, g++, pkg-config, libssl-dev, libdbus-1-dev, libglib2.0-dev, libavahi-client-dev, ninja-build, python3-venv, python3-dev, python3-pip, unzip, libgirepository1.0-dev, libcairo2-dev, libreadline-dev, generate-ninja]
    #override-prime:
    #  rm -r $CRAFT_PART_INSTALL
    stage:
      - -tests
      - -gen
      - -protocol_buffer
      - -python
      - -python-venv
      - -*.ninja
      - -*.map 
    organize:
      chip-tool: bin/chip-tool  
apps:
  chip-tool:
    command: bin/chip-tool
    plugs:
      - network
      - bluez
