name: chip-tool 
summary: Chip Tool Matter Controller
description: Refer to https://snapcraft.io/chip-tool
adopt-info: connectedhomeip
version: "v1.2.0.1+snap"

confinement: strict
grade: stable
license: Apache-2.0

base: core22

architectures:
  - build-on: amd64
  - build-on: arm64

layout:
  /mnt:
    bind: $SNAP_COMMON/mnt

parts:
  matter-sdk:
    plugin: matter-sdk
    matter-sdk-version: "1536ca20c5917578ca40ce509400e97b52751788" # use this commit with ptpython version fix; needs to be updated once matter sdk have a stable release
    matter-sdk-zap-version: "v2023.11.13"
      
  chip-tool:
    plugin: nil
    after: [matter-sdk]
    build-environment:
      - MATTER_SDK_ENV: ../../matter-sdk/build/matter_sdk_env
    override-build: |
      # Source the Matter SDK environment variables
      source $MATTER_SDK_ENV

      # Build the chip tool
      cd examples/chip-tool
      gn gen out/build
      ninja -C out/build
      
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp out/build/chip-tool $CRAFT_PART_INSTALL/bin/ 

apps:
  chip-tool:
    command: bin/chip-tool
    plugs:
      - network
      - network-bind
      - bluez
      - avahi-observe
      - process-control
    environment:
      # Replace the path for chip-tool configuration files
      TMPDIR: "/mnt"
