name: chip-tool 
summary: Chip Tool Matter Controller
description: Refer to https://snapcraft.io/chip-tool
adopt-info: connectedhomeip
version: "v1.2.0.1+snap"

confinement: strict
grade: stable
license: Apache-2.0

base: core22

architectures:
  - build-on: amd64
  - build-on: arm64

layout:
  /mnt:
    bind: $SNAP_COMMON/mnt

parts:
  chip-tool:
    plugin: matter
    # matter-branch: v1.2.0.1 
    # zap-version: 1
         
    override-build: |
      craftctl default
      cd $CRAFT_PART_BUILD/matter
      
      # The project writes its data to /tmp which isn't persisted.
      #
      # Setting TMPDIR env var when running the app isn't sufficient as 
      #  chip_[config,counter,factory,kvs].ini still get written under /tmp.
      # The chip-tool currently has no way of overriding the default paths to
      #   storage and security config files.
      #
      # Snap does not allow bind mounting a persistent directory on /tmp, 
      #  so we need to replace it in the source with another path, e.g. /mnt.
      # See the top-level layout definition which bind mounts a persisted
      #   directory within the confined snap space on /mnt.
      #
      # Replace storage paths:
      sed -i 's/\/tmp/\/mnt/g' src/platform/Linux/CHIPLinuxStorage.h
      # Replace key-value store path:
      sed -i 's/\/tmp/\/mnt/g' src/platform/Linux/CHIPPlatformConfig.h

      # To avoid activation errors, don't treat unset variables as error
      set +u 

      # Bootstrap with minimal "build" requirements
      source ./scripts/setup/bootstrap.sh --platform build

      # Build the chip tool
      ./scripts/examples/gn_build_example.sh examples/chip-tool ./build-examples
      
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp build-examples/chip-tool $CRAFT_PART_INSTALL/bin/

apps:
  chip-tool:
    command: bin/chip-tool
    plugs:
      - network
      - network-bind
      - bluez
      - avahi-observe
      - process-control
    environment:
      # Replace the path for chip-tool configuration files
      TMPDIR: "/mnt"
