name: chip-tool 
summary: Chip Tool Matter Controller
description: Refer to https://snapcraft.io/chip-tool
adopt-info: connectedhomeip
version: "v1.2.0.1+snap"

confinement: strict
grade: stable
license: Apache-2.0

base: core22

architectures:
  - build-on: amd64
  - build-on: arm64

layout:
  /mnt:
    bind: $SNAP_COMMON/mnt

parts:
  chip-tool:
    plugin: matter
    matter-sdk-version: "master"
    matter-zap-version: "v2023.11.13"
    override-build: |
      craftctl default
      cd $CRAFT_PART_BUILD/matter
      
      # Build the chip tool
      ./scripts/examples/gn_build_example.sh examples/chip-tool ./build-examples
      
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp build-examples/chip-tool $CRAFT_PART_INSTALL/bin/

apps:
  chip-tool:
    command: bin/chip-tool
    plugs:
      - network
      - network-bind
      - bluez
      - avahi-observe
      - process-control
    environment:
      # Replace the path for chip-tool configuration files
      TMPDIR: "/mnt"
