name: chip-tool 
version: master
summary: Chip Tool Matter Controller
description: |
  Chip Tool is a Matter controller being developed as part of the Connected Home IP project:
  https://github.com/project-chip/connectedhomeip.git

  The snap packaging makes it easy to run the Chip Tool on Linux distributions.

  For usage instructions, refer to https://github.com/farshidtz/chip-tool-snap/blob/main/README.md

confinement: strict
grade: devel
license: Apache-2.0

base: core22

architectures:
  - build-on: amd64
  - build-on: arm64

layout:
  /mnt:
    bind: $SNAP_DATA/mnt

parts:
  connectedhomeip:
    plugin: nil
    override-pull: |
      # shallow clone the project its submodules
      # TODO clone a specific tag or hash
      git clone https://github.com/project-chip/connectedhomeip.git --depth=1 .
      scripts/checkout_submodules.py --shallow --platform linux
      
  chip-tool:
    after: [connectedhomeip]
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/bin

      cd ../../connectedhomeip/src
      
      # The project writes its data to /tmp. Snap does not allow bind mounting
      #   a persistent directory on /tmp, so we need to replace it in the code.
      # Replace all /tmp directories with /mnt:
      sed -i 's/\/tmp/\/mnt/g' src/platform/Linux/CHIPLinuxStorage.h
      sed -i 's/\/tmp/\/mnt/g' src/platform/Linux/CHIPPlatformConfig.h

      # Setup the build environment
      set +u # do not treat unset variables as error
      # source scripts/activate.sh

      # build the chip tool
      ./scripts/examples/gn_build_example.sh examples/chip-tool ./build-examples
      # ./scripts/build/build_examples.py --target linux-x64-chip-tool build
      
      cp build-examples/chip-tool $CRAFT_PART_INSTALL/bin/
      # cp out/linux-*-chip-tool $CRAFT_PART_INSTALL/bin/chip-tool
    build-packages:
      - git
      - gcc
      - g++
      - pkg-config
      - libssl-dev
      - libdbus-1-dev
      - libglib2.0-dev
      - libavahi-client-dev
      - ninja-build
      - python3-venv
      - python3-dev
      - python3-pip
      - unzip
      - libgirepository1.0-dev
      - libcairo2-dev
      - libreadline-dev
      - generate-ninja

apps:
  chip-tool:
    command: bin/chip-tool
    plugs:
      - network
      - bluez
      # - avahi-control
      - avahi-observe
    # environment:
    ## This isn't sufficient
    #   TMPDIR: "/mnt"
